[
  # Import formatter configuration from dependencies
  import_deps: [:ecto, :ecto_sql, :phoenix],

  # Format files in subdirectories (like database migrations)
  subdirectories: ["priv/*/migrations"],

  # Use Phoenix LiveView HTML formatter for .heex files
  plugins: [Phoenix.LiveView.HTMLFormatter],

  # Specify which files to format
  inputs: [
    "*.{heex,ex,exs}",
    "{config,lib,test}/**/*.{heex,ex,exs}",
    "priv/*/seeds.exs"
  ],

  # Line length configuration (matches our style guide)
  line_length: 120,

  # Function formatting - prefer explicit parentheses for clarity
  normalize_bitstring_modifiers: true,
  normalize_charlists_as_sigils: true,

  # Import/alias sorting and grouping
  import_deps: [:ecto, :ecto_sql, :phoenix, :phoenix_ecto, :phoenix_html, :phoenix_live_view],

  # Locals without parentheses - common Phoenix/Ecto functions
  locals_without_parens: [
    # Ecto Schema
    field: 2,
    field: 3,
    belongs_to: 2,
    belongs_to: 3,
    has_one: 2,
    has_one: 3,
    has_many: 2,
    has_many: 3,
    many_to_many: 2,
    many_to_many: 3,
    embeds_one: 2,
    embeds_one: 3,
    embeds_many: 2,
    embeds_many: 3,
    timestamps: 0,
    timestamps: 1,

    # Ecto Query
    from: 1,
    from: 2,
    where: 2,
    where: 3,
    select: 2,
    select: 3,
    distinct: 2,
    order_by: 2,
    order_by: 3,
    group_by: 2,
    group_by: 3,
    having: 2,
    having: 3,
    limit: 2,
    offset: 2,
    lock: 2,
    join: 3,
    join: 4,
    join: 5,
    inner_join: 3,
    inner_join: 4,
    inner_join: 5,
    left_join: 3,
    left_join: 4,
    left_join: 5,
    right_join: 3,
    right_join: 4,
    right_join: 5,
    full_join: 3,
    full_join: 4,
    full_join: 5,
    cross_join: 3,
    cross_join: 4,
    cross_join: 5,
    preload: 2,
    preload: 3,

    # Ecto Changeset
    cast: 3,
    cast: 4,
    cast_assoc: 2,
    cast_assoc: 3,
    cast_embed: 2,
    cast_embed: 3,
    validate_required: 2,
    validate_required: 3,
    validate_acceptance: 2,
    validate_acceptance: 3,
    validate_change: 3,
    validate_change: 4,
    validate_confirmation: 2,
    validate_confirmation: 3,
    validate_exclusion: 3,
    validate_exclusion: 4,
    validate_format: 3,
    validate_format: 4,
    validate_inclusion: 3,
    validate_inclusion: 4,
    validate_length: 3,
    validate_number: 3,
    validate_subset: 3,
    validate_subset: 4,
    unique_constraint: 2,
    unique_constraint: 3,
    foreign_key_constraint: 2,
    foreign_key_constraint: 3,
    assoc_constraint: 2,
    assoc_constraint: 3,
    no_assoc_constraint: 2,
    no_assoc_constraint: 3,
    check_constraint: 2,
    check_constraint: 3,
    exclusion_constraint: 2,
    exclusion_constraint: 3,

    # Phoenix Controller
    pipe_through: 1,
    plug: 1,
    plug: 2,
    action_fallback: 1,

    # Phoenix Router
    resources: 2,
    resources: 3,
    resources: 4,
    resource: 2,
    resource: 3,
    resource: 4,
    get: 2,
    get: 3,
    get: 4,
    post: 2,
    post: 3,
    post: 4,
    put: 2,
    put: 3,
    put: 4,
    patch: 2,
    patch: 3,
    patch: 4,
    delete: 2,
    delete: 3,
    delete: 4,
    options: 2,
    options: 3,
    options: 4,
    connect: 2,
    connect: 3,
    connect: 4,
    trace: 2,
    trace: 3,
    trace: 4,
    head: 2,
    head: 3,
    head: 4,
    forward: 2,
    forward: 3,
    forward: 4,
    scope: 2,
    scope: 3,
    live: 2,
    live: 3,
    live: 4,
    live_session: 2,
    live_session: 3,

    # Phoenix LiveView
    assign: 2,
    assign: 3,
    assign_new: 3,
    update: 3,
    push_event: 3,
    push_redirect: 2,
    push_navigate: 2,
    put_flash: 3,
    clear_flash: 1,
    clear_flash: 2,

    # Testing
    assert: 1,
    assert: 2,
    refute: 1,
    refute: 2,
    assert_raise: 2,
    assert_raise: 3,
    assert_receive: 1,
    assert_receive: 2,
    assert_receive: 3,
    refute_receive: 1,
    refute_receive: 2,
    refute_receive: 3,
    assert_received: 1,
    assert_received: 2,
    refute_received: 1,
    refute_received: 2,
    flunk: 0,
    flunk: 1,

    # ExUnit setup
    setup: 1,
    setup: 2,
    setup_all: 1,
    setup_all: 2,
    describe: 2,
    test: 1,
    test: 2,
    test: 3
  ]
]
