
# Base configuration shared between environments
services:
  db:
    image: postgres:17.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  test_db:
    image: postgres:17.5
    environment:
      POSTGRES_DB: gatherly_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    image: elixir:1.18.4-otp-28
    working_dir: /app
    volumes:
      - .:/app
    command: >
      bash -c "
        apt-get update -qq &&
        apt-get install -y postgresql-client inotify-tools &&
        mix local.hex --force &&
        mix local.rebar --force &&
        if [ -f mix.exs ]; then mix deps.get; fi &&
        tail -f /dev/null
      "