# CI-specific overrides for optimized testing
services:
  # Use test_db for CI tests with optimizations
  test_db:
    # Use tmpfs for speed in CI
    tmpfs:
      - /var/lib/postgresql/data
    # Faster healthcheck for CI
    healthcheck:
      interval: 2s
      timeout: 5s
      retries: 10
    # No port mapping - CI doesn't need external access
    ports: []

  app:
    environment:
      MIX_ENV: dev
      DATABASE_URL: postgres://postgres:postgres@test_db:5432/gatherly_test
      SECRET_KEY_BASE: VcplVBtlc4FRIRnto8WvuQK5IehyUj0LBJ1N86+WH5r2PxHbjaJZkW97Tgj13IL6
      TOKEN_SIGNING_SECRET: test_token_signing_secret_for_ci_only
      PHX_HOST: localhost
      PHX_PORT: 4000
      GOOGLE_CLIENT_ID: test_client_id
      GOOGLE_CLIENT_SECRET: test_client_secret
      # CI-specific optimizations
      ERL_AFLAGS: "-kernel shell_history enabled"
    volumes:
      - .:/app
    depends_on:
      test_db:
        condition: service_healthy
    # No port mapping needed for CI
    ports: []
    # No tty/stdin for CI
    tty: false
    stdin_open: false
    # Simple command that keeps container running
    command: tail -f /dev/null