# CI-specific overrides for optimized testing
services:
  # Use test_db for CI tests with optimizations
  test_db:
    # Use tmpfs for speed in CI
    tmpfs:
      - /var/lib/postgresql/data
    # Faster healthcheck for CI
    healthcheck:
      interval: 2s
      timeout: 5s
      retries: 10
    # No port mapping - CI doesn't need external access
    ports: []

  app:
    environment:
      MIX_ENV: test
      DATABASE_URL: postgres://postgres:postgres@test_db:5432/gatherly_test
      SECRET_KEY_BASE: test_secret_key_base_for_ci_only_do_not_use_in_production
      TOKEN_SIGNING_SECRET: test_token_signing_secret_for_ci_only
      PHX_HOST: localhost
      PHX_PORT: 4000
      GOOGLE_CLIENT_ID: test_client_id
      GOOGLE_CLIENT_SECRET: test_client_secret
      # CI-specific optimizations
      ERL_AFLAGS: "-kernel shell_history enabled"
    volumes:
      - .:/app
      # Ephemeral volumes for CI (not defined in volumes section)
      - /app/deps
      - /app/_build
      - /root/.mix
    depends_on:
      test_db:
        condition: service_healthy
    # No port mapping needed for CI
    ports: []
    # No tty/stdin for CI
    tty: false
    stdin_open: false
    healthcheck:
      test: ["CMD-SHELL", "test -f /app/mix.exs && mix help > /dev/null"]
      interval: 2s
      timeout: 10s
      retries: 15
    command: >
      bash -c "
        apt-get update -qq &&
        apt-get install -y postgresql-client &&
        mix local.hex --force &&
        mix local.rebar --force &&
        MIX_ENV=test mix deps.get &&
        MIX_ENV=test mix deps.compile &&
        tail -f /dev/null
      "