version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gatherly_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - deps:/app/deps
      - _build:/app/_build
      - /app/assets/node_modules
    environment:
      - MIX_ENV=dev
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/gatherly_dev
      - SECRET_KEY_BASE=your-secret-key-base
    command: >
      sh -c "mix deps.get && 
             mix ecto.create && 
             mix ecto.migrate && 
             mix phx.server"
    stdin_open: true
    tty: true

volumes:
  postgres_data:
  deps:
  _build:
  node_modules:
