app = "gatherly"
primary_region = "sjc"

[build]

[env]
  PHX_HOST = "gatherly.qingbo.us"
  PORT = "8080"
  MIX_ENV = "prod"
  PHX_SERVER = "true"
  RELEASE_COOKIE = "gatherly-secret-cookie-change-in-production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[[statics]]
  guest_path = "/app/priv/static"
  url_prefix = "/assets"

[deploy]
  release_command = "./bin/gatherly eval \"Gatherly.Release.migrate\""

[checks]
  [checks.health]
    type = "http"
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health"
    headers = {}