# Fly.io configuration for staging environment
app = "gatherly-staging"
primary_region = "sjc"

[build]

[env]
  MIX_ENV = "prod"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[[statics]]
  guest_path = "/app/lib/gatherly_web-0.1.0/priv/static"
  url_prefix = "/static/"