name: Deploy to Fly.io

on:
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types: [completed]
  workflow_dispatch:
    inputs:
      skip_ci:
        description: "Skip CI checks (use existing artifacts)"
        required: false
        default: false
        type: boolean

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

permissions:
  contents: read
  actions: read

jobs:
  # Deploy to production environment
  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-22.04
    if: |
      (github.event.workflow_run.conclusion == 'success') ||
      (github.event_name == 'workflow_dispatch')
    environment:
      name: production
      url: https://gatherly.fly.dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to production
        run: |
          echo "🚀 Deploying to production environment..."
          flyctl deploy --app gatherly --verbose
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Run post-deployment health checks
        run: |
          echo "🔍 Running production health checks..."

          # Wait for deployment to be ready
          sleep 45

          # Check main application health
          if curl -f --max-time 30 https://gatherly.fly.dev/; then
            echo "✅ Main domain health check passed"
          else
            echo "❌ Main domain health check failed"
            exit 1
          fi

          # Check custom domain if configured
          if curl -f --max-time 30 https://gatherly.qingbo.us/; then
            echo "✅ Custom domain health check passed"
          else
            echo "⚠️ Custom domain health check failed (may be DNS propagation)"
          fi

      - name: Notify production deployment success
        if: success()
        run: |
          echo "🎉 Production deployment successful!"
          echo "📱 App URL: https://gatherly.fly.dev"
          echo "🌐 Custom domain: https://gatherly.qingbo.us"
          echo "✨ Deployment completed at $(date)"
